component: http
name: http-nestjs-azXWU1b5Z
org: '1305763203'
app: member-manages-api
stage: dev
inputs:
  region: ap-shanghai
  src:
    src: ./
    dist: ./
    hook: npm run build
    exclude:
      - .env
      - 'node_modules/**'
  faas:
    runtime: Nodejs12.16
    eip: true
    timeout: 3
    memorySize: 64
    tags: []
    framework: nestjs
    environments: []
    # vpc:
    #   vpcId: 'vpc-d4gajp9o'
    #   subnetId: 'subnet-p5pm99rr'
    layers:
      - name: member-manages-api-layer
        version: 2
  apigw:
    timeout: 60
    protocols:
      - http
      - https
    environment: release
    customDomains: []
